In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving bdPredicao.xlsx to bdPredicao (1).xlsx

In [ ]:
df = pd.read_excel(next(iter(uploaded.keys())))
df

,id_cooperado,pf_ou_pj,especialidade,competencia,nacionalidade,situacao_epoca_do_repasse,hospital,estado_civil,grau_instrucao,cooperado_origem_de_conversao,cooperado_destino_de_conversao,participa_servico_especial,valor_procedimento_a_repassar,valor_lancamento_eventual_a_repassar,valor_predicao_liquido
0,1719,pf,Médico cirurgião geral,2021-01-01,Brasileira,Licenciado,P ATENDIMENTO,Solteiro,Superior,0,0,0,0.0,0.0,0.0
1,1719,pf,Médico cirurgião geral,2021-02-01,Brasileira,Licenciado,P ATENDIMENTO,Solteiro,Superior,0,0,0,0.0,0.0,0.0
2,1719,pf,Médico cirurgião geral,2021-03-01,Brasileira,Licenciado,P ATENDIMENTO,Solteiro,Superior,0,0,0,0.0,0.0,0.0
3,1719,pf,Médico cirurgião geral,2021-04-01,Brasileira,Licenciado,P ATENDIMENTO,Solteiro,Superior,0,0,0,0.0,0.0,0.0
4,1719,pf,Médico cirurgião geral,2021-05-01,Brasileira,Licenciado,P ATENDIMENTO,Solteiro,Superior,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74479,24883,pf,Médico generalista,2022-02-01,Brasileira,Ativo,CONSULTORIOS,Casado,Superior,0,0,0,0.0,0.0,0.0
74480,24883,pf,Médico generalista,2022-03-01,Brasileira,Ativo,CONSULTORIOS,Casado,Superior,0,0,0,0.0,0.0,0.0
74481,24883,pf,Médico generalista,2022-04-01,Brasileira,Ativo,CONSULTORIOS,Casado,Superior,0,0,0,0.0,0.0,0.0
74482,24883,pf,Médico generalista,2022-05-01,Brasileira,Ativo,CONSULTORIOS,Casado,Superior,0,0,0,0.0,0.0,0.0
74483,24883,pf,Médico generalista,2022-06-01,Brasileira,ativo,CONSULTORIOS,Casado,Superior,0,0,0,0.0,0.0,0.0

In [ ]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

In [ ]:
df['pf_ou_pj'].isnull().sum()

0

In [ ]:
df['competencia'].isnull().sum()

0

Registros sem nacionalidade foram setados com a moda

In [ ]:
df['nacionalidade'].fillna(('Brasileira'), inplace=True)

Como se tratam de dados sem especialidades, preferi criar um item que demonstra que não tem especialidade. Esses dados possuem valores de procedimentos e lançamentos eventuais que não podem ser ignorados. Também se trata de registros com definição difícil de fazer.

In [ ]:
df['especialidade'].fillna(('Sem Especialidade'), inplace=True)

In [ ]:
df['situacao_epoca_do_repasse'].isnull().sum()

0

In [ ]:
df['hospital'].isnull().sum()

5508

Como se tratam de dados sem hospitais, 
preferi criar um item  que demonstra que não tem hospital. Esses dados possuem valores de procedimentos e 
lançamentos eventuais que não podem ser ignorados. Também se trata de registros com definição difícil de fazer.

In [ ]:
df['hospital'].fillna(('Sem Hospital'), inplace=True)

Como se trata de dados sem estado civíl, 
preferi criar um estado civíl com descrição que demonstra que não tem informação por possuir alguns valores de procedimentos e 
lançamentos eventuais que não podem ser ignorados. Podemos descobrir algum conhecimento aqui no que se refere a ter mais tempo para atuar

In [ ]:
df['estado_civil'].fillna(('Sem'), inplace=True)

Registros sem grau de instrução se referem a cadastros de empresas.
Será adotado um ítem pj nesse caso.

In [ ]:

df['grau_instrucao'].fillna(('pj'), inplace=True)

Atributos categóricos que foram convertidos utilizando one hot encoding. 
Como não se tratam de features que tem sentido de ordenação,foi escolhido
o one hot encoding para que o modelo não interprete uma relação de ordem.
Podemos ter problemas com memória nesse caso mas inicialmente trabalharemos da forma ensinada 
na literatura.

In [ ]:
df = pd.get_dummies(df, columns = ['estado_civil'])
df = pd.get_dummies(df, columns = ['nacionalidade'])
df = pd.get_dummies(df, columns = ['situacao_epoca_do_repasse'])
df

,id_cooperado,pf_ou_pj,competencia,grau_instrucao,cooperado_origem_de_conversao,cooperado_destino_de_conversao,participa_servico_especial,valor_procedimento_a_repassar,valor_lancamento_eventual_a_repassar,valor_predicao_liquido,...,situacao_epoca_do_repasse_Ativo,situacao_epoca_do_repasse_Demitido,situacao_epoca_do_repasse_Eliminado,situacao_epoca_do_repasse_Excluído,situacao_epoca_do_repasse_Falecido,situacao_epoca_do_repasse_Inativo,situacao_epoca_do_repasse_Inativo,situacao_epoca_do_repasse_Licenciado,situacao_epoca_do_repasse_Licenciado,situacao_epoca_do_repasse_ativo
0,1719,pf,2021-01-01,Superior,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
1,1719,pf,2021-02-01,Superior,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
2,1719,pf,2021-03-01,Superior,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
3,1719,pf,2021-04-01,Superior,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
4,1719,pf,2021-05-01,Superior,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74479,24883,pf,2022-02-01,Superior,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74480,24883,pf,2022-03-01,Superior,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74481,24883,pf,2022-04-01,Superior,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74482,24883,pf,2022-05-01,Superior,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74483,24883,pf,2022-06-01,Superior,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
def generate_labelencoder(atts):
  for attr in atts:
    df[attr] = le.fit_transform(df[attr])
  return df

Features categóricas com domínio binário ou com sentido de ordenação. Convertidas utilizando o Label Encoder

In [ ]:

df  = generate_labelencoder(['pf_ou_pj','grau_instrucao','competencia','hospital','especialidade'])

In [ ]:
df

,id_cooperado,pf_ou_pj,competencia,grau_instrucao,cooperado_origem_de_conversao,cooperado_destino_de_conversao,participa_servico_especial,valor_procedimento_a_repassar,valor_lancamento_eventual_a_repassar,valor_predicao_liquido,...,situacao_epoca_do_repasse_Ativo,situacao_epoca_do_repasse_Demitido,situacao_epoca_do_repasse_Eliminado,situacao_epoca_do_repasse_Excluído,situacao_epoca_do_repasse_Falecido,situacao_epoca_do_repasse_Inativo,situacao_epoca_do_repasse_Inativo,situacao_epoca_do_repasse_Licenciado,situacao_epoca_do_repasse_Licenciado,situacao_epoca_do_repasse_ativo
0,1719,0,0,2,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
1,1719,0,1,2,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
2,1719,0,2,2,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
3,1719,0,3,2,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
4,1719,0,4,2,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74479,24883,0,13,2,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74480,24883,0,14,2,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74481,24883,0,15,2,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74482,24883,0,16,2,0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
74483,24883,0,17,2,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

Coluna id_cooperado foi excluída. Passar essa coluna para o modelo pode gerar um Overfitting. Além de não fazer sentido passar tal informação, atrapalharia na generalização do aprendizado.

In [ ]:
df = df.drop(['id_cooperado'], axis=1)

In [ ]:
df

,pf_ou_pj,competencia,grau_instrucao,cooperado_origem_de_conversao,cooperado_destino_de_conversao,participa_servico_especial,valor_procedimento_a_repassar,valor_lancamento_eventual_a_repassar,valor_predicao_liquido,hospital_BALEIA,...,situacao_epoca_do_repasse_Ativo,situacao_epoca_do_repasse_Demitido,situacao_epoca_do_repasse_Eliminado,situacao_epoca_do_repasse_Excluído,situacao_epoca_do_repasse_Falecido,situacao_epoca_do_repasse_Inativo,situacao_epoca_do_repasse_Inativo,situacao_epoca_do_repasse_Licenciado,situacao_epoca_do_repasse_Licenciado,situacao_epoca_do_repasse_ativo
0,0,0,2,0,0,0,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,1,2,0,0,0,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,2,2,0,0,0,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,3,2,0,0,0,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,4,2,0,0,0,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74479,0,13,2,0,0,0,0.0,0.0,0.0,0,...,1,0,0,0,0,0,0,0,0,0
74480,0,14,2,0,0,0,0.0,0.0,0.0,0,...,1,0,0,0,0,0,0,0,0,0
74481,0,15,2,0,0,0,0.0,0.0,0.0,0,...,1,0,0,0,0,0,0,0,0,0
74482,0,16,2,0,0,0,0.0,0.0,0.0,0,...,1,0,0,0,0,0,0,0,0,0
74483,0,17,2,0,0,0,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,1